# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: Codetoil.CurvedSpacetime
PackageVersion: ${version}
ManifestType: version
DefaultLocale: en-US
Publisher: Codetoil
PackageName: CurvedSpacetime
ManifestVersion: 1.10.0
