# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Codetoil.CurvedSpacetime
PackageVersion: 0.1.0-build.61
ManifestType: installer
Installers:
  - Architecture: x64
    InstallerType: zip
    InstallerUrl: https://github.com/Codetoil/curved-spacetime/releases/download/0.1.0-build.61/curved-spacetime-closed-world-native-variant-windows-x64-0.1.0-build.61.zip
    InstallerSha256: C9AF3080CB1D0C82B33C98585504246309C5109FA595906E37A690DC17A72D73
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: ./curved-spacetime-0.1.0-SNAPSHOT-windows-x64.exe
ManifestVersion: 1.10.0
