name: Publish Archive (Native)

on:
  release:
    types: [ published ]

jobs:
  publish-curved-spacetime-closed-linux-x64:
    name: Publish curved-spacetime (Closed World Native Variant) Linux x64
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Compile
        run: ./gradlew :curved-spacetime-closed-world-loader-module:nativeCompile
      - run: git archive --format=tar.gz -o ./archive-closed-world-native-linux-x64/source.tar.gz HEAD
      - run: zip -r ../curved-spacetime-closed-world-native-variant-linux-x64-${{ github.ref_name }}.zip .
        working-directory: archive-closed-world-native-linux-x64
      - name: Publish
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./curved-spacetime-closed-world-native-variant-linux-x64-${{ github.ref_name }}.zip
  publish-curved-spacetime-closed-linux-arm64:
    name: Publish curved-spacetime (Closed World Native Variant) Linux arm64
    runs-on: ubuntu-24.04-arm

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Compile
        run: ./gradlew :curved-spacetime-closed-world-loader-module:nativeCompile
      - run: git archive --format=tar.gz -o ./archive-closed-world-native-linux-arm64/source.tar.gz HEAD
      - run: zip -r ../curved-spacetime-closed-world-native-variant-linux-arm64-${{ github.ref_name }}.zip .
        working-directory: archive-closed-world-native-linux-arm64
      - name: Publish
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./curved-spacetime-closed-world-native-variant-linux-arm64-${{ github.ref_name }}.zip
  publish-curved-spacetime-closed-windows-x64:
    name: Publish curved-spacetime (Closed World Native Variant) Windows x64
    runs-on: windows-2025

    permissions:
      contents: write
    outputs:
      sha1: ${{ steps.upload_archive_sha1.outputs.sha1 }}

    steps:
      - uses: actions/checkout@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Compile
        run: ./gradlew :curved-spacetime-closed-world-loader-module:nativeCompile
      - run: git archive --format=tar.gz -o ./archive-closed-world-native-windows-x64/source.tar.gz HEAD
      - run: Compress-Archive -Path ./archive-closed-world-native-windows-x64/* -DestinationPath ./curved-spacetime-closed-world-native-variant-windows-x64-${{ github.ref_name }}.zip
      - id: upload_archive_sha1
        run: echo "sha1=$(sha1sum ./curved-spacetime-closed-world-native-variant-windows-x64-${{ github.ref_name }}.zip)" | sed 's/\s.*$// > "${GITHUB_OUTPUT}"
      - name: Publish
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./curved-spacetime-closed-world-native-variant-windows-x64-${{ github.ref_name }}.zip
  publish-curved-spacetime-closed-macos-x64:
    name: Publish curved-spacetime (Closed World Native Variant) macOS x64
    runs-on: macos-15-intel

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Compile
        run: ./gradlew :curved-spacetime-closed-world-loader-module:nativeCompile
      - run: git archive --format=tar.gz -o ./archive-closed-world-native-macos-x64/source.tar.gz HEAD
      - run: zip -r ../curved-spacetime-closed-world-native-variant-macos-x64-${{ github.ref_name }}.zip .
        working-directory: archive-closed-world-native-macos-x64
      - name: Publish
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./curved-spacetime-closed-world-native-variant-macos-x64-${{ github.ref_name }}.zip
  publish-curved-spacetime-closed-macos-arm64:
    name: Publish curved-spacetime (Closed World Native Variant) macOS arm64
    runs-on: macos-26

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Compile
        run: ./gradlew :curved-spacetime-closed-world-loader-module:nativeCompile
      - run: git archive --format=tar.gz -o ./archive-closed-world-native-macos-arm64/source.tar.gz HEAD
      - run: zip -r ../curved-spacetime-closed-world-native-variant-macos-arm64-${{ github.ref_name }}.zip .
        working-directory: archive-closed-world-native-macos-arm64
      - name: Publish
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./curved-spacetime-closed-world-native-variant-macos-arm64-${{ github.ref_name }}.zip
  # Done in same script for now
  publish-winget-to-github-pages:
    runs-on: windows-2025
    # Add a dependency to the build job
    needs: publish-curved-spacetime-closed-windows-x64
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions: # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    steps:
      - uses: actions/checkout@v5
        with:
          ref: pages

#      - env:
#          SHA1: ${{needs.upload_archive_sha1.outputs.sha1}}
      - name: Push update to repo
        run: |
          git add .
          git config --global user.name 'Codetoil'
          git config --global user.email 'codetoil@users.noreply.github.com'
          git commit -am "Automated update ${{ github.ref_name }}"
          git push