name: Publish Archive (Native)

on:
  release:
    types: [ created ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-curved-spacetime-closed-linux-x64:
    name: Publish curved-spacetime (Closed Native Variant) Linux x64
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Compile
        run: ./gradlew :curved-spacetime-closed-loader-module:nativeCompile
      - run: git archive --format=tar.gz -o ./archive-closed-native-linux-x64/source.tar.gz HEAD
      - run: zip -r curved-spacetime-closed-native-variant-${{ env.VERSION }}-${{ github.sha }}-linux-x64.zip .
        working-directory: archive-closed-native-linux-x64
      - name: Publish
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: curved-spacetime-closed-native-variant-${{ env.VERSION }}-${{ github.sha }}-linux-x64.zip
  publish-curved-spacetime-closed-linux-arm64:
    name: Publish curved-spacetime (Closed Native Variant) Linux arm64
    runs-on: ubuntu-24.04-arm

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Compile
        run: ./gradlew :curved-spacetime-closed-loader-module:nativeCompile
      - run: git archive --format=tar.gz -o ./archive-closed-native-linux-arm64/source.tar.gz HEAD
      - run: zip -r curved-spacetime-closed-native-variant-${{ env.VERSION }}-${{ github.sha }}-linux-arm64.zip .
        working-directory: archive-closed-native-linux-arm64
      - name: Publish
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: curved-spacetime-closed-native-variant-${{ env.VERSION }}-${{ github.sha }}-linux-arm64.zip
  publish-curved-spacetime-closed-windows-x64:
    name: Publish curved-spacetime (Closed Native Variant) Windows x64
    runs-on: windows-2025

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Compile
        run: ./gradlew :curved-spacetime-closed-loader-module:nativeCompile
      - run: git archive --format=tar.gz -o ./archive-closed-native-windows-x64/source.tar.gz HEAD
      - run: zip -r curved-spacetime-closed-native-variant-${{ env.VERSION }}-${{ github.sha }}-windows-x64.zip .
        working-directory: archive-closed-native-windows-x64
      - name: Publish
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: curved-spacetime-closed-native-variant-${{ env.VERSION }}-${{ github.sha }}-windows-x64.zip
  publish-curved-spacetime-closed-macos-x64:
    name: Publish curved-spacetime (Closed Native Variant) macOS x64
    runs-on: macos-15-intel

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Compile
        run: ./gradlew :curved-spacetime-closed-loader-module:nativeCompile
      - run: git archive --format=tar.gz -o ./archive-closed-native-macos-x64/source.tar.gz HEAD
      - run: zip -r curved-spacetime-closed-native-variant-${{ env.VERSION }}-${{ github.sha }}-macos-x64.zip .
        working-directory: archive-closed-native-macos-x64
      - name: Publish
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: curved-spacetime-closed-native-variant-${{ env.VERSION }}-${{ github.sha }}-macos-x64.zip
  publish-curved-spacetime-closed-macos-arm64:
    name: Publish curved-spacetime (Closed Native Variant) macOS arm64
    runs-on: macos-26

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Compile
        run: ./gradlew :curved-spacetime-closed-loader-module:nativeCompile
      - run: git archive --format=tar.gz -o ./archive-closed-native-macos-arm64/source.tar.gz HEAD
      - run: zip -r curved-spacetime-closed-native-variant-${{ env.VERSION }}-${{ github.sha }}-macos-arm64.zip .
        working-directory: archive-closed-native-macos-arm64
      - name: Publish
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: curved-spacetime-closed-native-variant-${{ env.VERSION }}-${{ github.sha }}-macos-arm64.zip