name: Publish GitHub Pages

on:
  release:
    types: [ published ]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  javadoc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Create javadocs
        id: javadocs
        run: ./gradlew :javadoc
      - name: Upload javadocs as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          name: javadoc
          path: build/docs/javadoc

  publish-to-github-pages:
    runs-on: ubuntu-24.04
    # Add a dependency to the build job
    needs: javadoc
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: pages
      - name: Download the javadocs from earlier
        uses: actions/download-artifact@v6
        with:
          name: javadoc
      - run: mkdir -p javadoc/curved-spacetime/${{ github.ref_name }}
      - run: unzip -d javadoc/curved-spacetime/${{ github.ref_name }} ${{github.workspace}}/javadoc
      - name: Preform Update
        run: |
          git add .
          git config --global user.name 'Codetoil'
          git config --global user.email 'codetoil@users.noreply.github.com'
          git commit -am "Automated update"
          git push