name: Publish Archive (Native)

on:
  release:
    types: [ published ]

jobs:
  publish-curved-spacetime-closed-linux-x64:
    name: Publish curved-spacetime (Closed-World Native Variant) Linux x64
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Compile
        run: ./gradlew :curved-spacetime-closed-world-loader-module:nativeCompile
      - run: git archive --format=tar.gz -o ./archive-closed-world-native-linux-x64/source.tar.gz HEAD
      - run: zip -r ../curved-spacetime-closed-world-native-variant-linux-x64-${{ github.ref_name }}.zip .
        working-directory: archive-closed-world-native-linux-x64
      - name: Publish
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./curved-spacetime-closed-world-native-variant-linux-x64-${{ github.ref_name }}.zip
  publish-curved-spacetime-closed-linux-arm64:
    name: Publish curved-spacetime (Closed-World Native Variant) Linux arm64
    runs-on: ubuntu-24.04-arm

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Compile
        run: ./gradlew :curved-spacetime-closed-world-loader-module:nativeCompile
      - run: git archive --format=tar.gz -o ./archive-closed-world-native-linux-arm64/source.tar.gz HEAD
      - run: zip -r ../curved-spacetime-closed-world-native-variant-linux-arm64-${{ github.ref_name }}.zip .
        working-directory: archive-closed-world-native-linux-arm64
      - name: Publish
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./curved-spacetime-closed-world-native-variant-linux-arm64-${{ github.ref_name }}.zip
  publish-curved-spacetime-closed-windows-x64:
    name: Publish curved-spacetime (Closed-World Native Variant) Windows x64
    runs-on: windows-2025

    permissions:
      contents: write
      actions: write

    steps:
      - uses: actions/checkout@v6
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Compile
        run: ./gradlew :curved-spacetime-closed-world-loader-module:nativeCompile
      - run: git archive --format=tar.gz -o ./archive-closed-world-native-windows-x64/source.tar.gz HEAD
      - run: Compress-Archive -Path ./archive-closed-world-native-windows-x64/* -DestinationPath ./curved-spacetime-closed-world-native-variant-windows-x64-${{ github.ref_name }}.zip
      - name: Publish
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./curved-spacetime-closed-world-native-variant-windows-x64-${{ github.ref_name }}.zip
      - run: gh workflow run publish-github-pages-winget.yml -f version="${{ github.ref_name }}" -f archive_hash="$(Get-FileHash -Path curved-spacetime-closed-world-native-variant-windows-x64-${{ github.ref_name }}.zip -Algorithm SHA256 | Select-Object -ExpandProperty Hash)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-curved-spacetime-closed-macos-arm64:
    name: Publish curved-spacetime (Closed-World Native Variant) macOS arm64
    runs-on: macos-26

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Compile
        run: ./gradlew :curved-spacetime-closed-world-loader-module:nativeCompile
      - run: git archive --format=tar.gz -o ./archive-closed-world-native-macos-arm64/source.tar.gz HEAD
      - run: zip -r ../curved-spacetime-closed-world-native-variant-macos-arm64-${{ github.ref_name }}.zip .
        working-directory: archive-closed-world-native-macos-arm64
      - name: Publish
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./curved-spacetime-closed-world-native-variant-macos-arm64-${{ github.ref_name }}.zip